poseidon/github-runner

- Dockerfile.amd64
- Dockerfile.arm64
- Makefile
- scripts/build
* Github Actions repo refers to their amd64 artifact as x64
> Build multiarch image with amd64 and arm64 variants

- README.md
- scripts/start
* Accept an EPHEMERAL environment variable to configure the ephemeral parameter
Rel: https://github.blog/changelog/2021-09-20-github-actions-ephemeral-self-hosted-runners-new-webhooks-for-auto-scaling/
> Add --ephemeral parameter to GitHub runner by default

- Dockerfile.amd64
- Dockerfile.arm64
* https://github.com/actions/runner/releases/tag/v2.296.2
> Update GitHub Actions Runner from v2.296.1 to v2.296.2

- Dockerfile.amd64
- Dockerfile.arm64
* https://github.com/actions/runner/releases/tag/v2.297.0
> Update Github Actions Runner from v2.296.2 to v2.297.0

- Dockerfile.amd64
- Dockerfile.arm64
* https://github.com/actions/runner/releases/tag/v2.298.2
> Update GitHub Actions Runner from v2.297.0 to v2.298.2

- Dockerfile.amd64
- Dockerfile.arm64
* https://github.com/actions/runner/releases/tag/v2.299.1
> Update GitHub Actions Runner from v2.298.2 to v2.299.1

- Makefile
- README.md
- cmd/gha/main.go
- go.mod
* Keeping the source code in deploybot-app and publishing the container image to quay.io/poseidon is unusual. Just keep it in the poseidon org
> Change organization from deploybot-app to poseidon

- Dockerfile.amd64
- Dockerfile.arm64
* https://github.com/actions/runner/releases/tag/v2.300.1
> Update GitHub Actions Runner from v2.299.1 to v2.300.1

- Dockerfile.amd64
- Dockerfile.arm64
* https://github.com/actions/runner/releases/tag/v2.302.1
> Update GitHub Actions Runner from v2.301.1 to v2.302.1

- Dockerfile.amd64
- Dockerfile.arm64
* https://github.com/actions/runner/releases/tag/v2.303.0
> Update GitHub Actions Runner from v2.302.1 to v2.303.0

- Dockerfile.amd64
- Dockerfile.arm64
- README.md
- scripts/build
* Use fedora internally, but for external examples and demos it can be useful to have the base image be debian/ubuntu
* Use docker.io/ubuntu:20.04 (rather than 22.04) because the GitHub Actions Runner requests system packages from 18.04 and 20.04, they don't seem to be quite up-to-date
Rel: https://github.com/actions/runner/blob/main/docs/start/envlinux.md#full-dependencies-list
> Change the base image from fedora to ubuntu

- Dockerfile.amd64
- Dockerfile.arm64
* https://github.com/actions/runner/releases/tag/v2.305.0
> Update GitHub Actions runner from v2.304 to v2.305

- Dockerfile.amd64
- Dockerfile.arm64
* https://github.com/actions/runner/releases/tag/v2.306.0
> Update GitHub Actions runner from v2.305 to v2.306

- Dockerfile.amd64
- Dockerfile.arm64
* https://github.com/actions/runner/releases/tag/v2.307.0
> Update GitHub Actions Runner from v2.306.0 to v2.307.0

- Dockerfile.amd64
- Dockerfile.arm64
* https://github.com/actions/runner/releases/tag/v2.307.1
> Update GitHub Actions Runner from v2.307.0 to v2.307.1

- Dockerfile.amd64
- Dockerfile.arm64
* https://github.com/actions/runner/releases/tag/v2.309.0
> Update GitHub Actions Runner from v2.308.0 to v2.309.0

- Dockerfile.amd64
- Dockerfile.arm64
* https://github.com/actions/runner/releases/tag/v2.310.2
> Update GitHub Actions Runner from v2.309.0 to v2.310.2

- Dockerfile.amd64
- Dockerfile.arm64
* https://github.com/actions/runner/releases/tag/v2.311.0
> Update GitHub Actions Runner from v2.310.2 to v2.311.0

- Dockerfile.amd64
- Dockerfile.arm64
* https://github.com/actions/runner/releases/tag/v2.312.0
> Update GitHub Actions Runner from v2.311.0 to v2.312.0

- Dockerfile.amd64
- Dockerfile.arm64
* https://github.com/actions/runner/releases/tag/v2.313.0
> Update GitHub Actions runner from 2.312.0 to 2.313.0

- Dockerfile.amd64
- Dockerfile.arm64
* https://github.com/actions/runner/releases/tag/v2.314.1
> Update GitHub Actions Runner from v2.313.0 to v2.314.1

- Dockerfile.amd64
- Dockerfile.arm64
* https://github.com/actions/runner/releases/tag/v2.315.0
> Update GitHub Action Runner from v2.314.1 to v2.315.0

- Dockerfile.amd64
- Dockerfile.arm64
* https://github.com/actions/runner/releases/tag/v2.316.1
> Update GitHub Actions Runner from v2.315.0 to v2.316.1

- Dockerfile.amd64
- Dockerfile.arm64
- Makefile
- scripts/build
* Update packages required by the GitHub Actions Runner to their Ubuntu 24.04 equivalents
> Update base image from 20.04 to 24.04

- Dockerfile.amd64
- Dockerfile.arm64
- scripts/build
- scripts/start
* When running many GitHub Runners, I sometimes see them exit uncleanly because GitHub's config.sh races with shutting down the Listener which can causes Pods to error
* Help GitHub along by killing the Runner.Listener which might reduce the frequency here, though not a real solution
```
An error occurred: Access denied. System:ServiceIdentity;DDDDDDDD-DDDD-DDDD-DDDD-DDDDDDDDDDDD needs View permissions to perform the action.
```
Rel: https://github.com/actions/runner/issues/971
> Revert to ubuntu:20.04 and workaround cleanup bug

- Dockerfile.amd64
- Dockerfile.arm64
- scripts/build
- scripts/start
* Github cleanup bug isn't solved by the workaround, I've solved it separately by allowing unclean pod failures in jobs.
> Revert "Revert to ubuntu:20.04 and workaround cleanup bug"

- Dockerfile.amd64
- Dockerfile.arm64
* https://github.com/actions/runner/releases/tag/v2.317.0
> Update GitHub Actions Runner from v2.316.1 to v2.317.0

- Makefile
* Resolve symlinks to env files or secrets to mount into the github-runner container when developing or debugging
> Adapt Makefile run target to allow symlinks to secrets

- Dockerfile.amd64
- Dockerfile.arm64
* https://github.com/actions/runner/releases/tag/v2.318.0
> Update GitHub Actions runner from v2.317.0 to v2.318.0

- Dockerfile.amd64
- Dockerfile.arm64
* https://github.com/actions/runner/releases/tag/v2.321.0
> Update GitHub Actions Runner from v2.320.0 to v2.321.0

- Dockerfile.amd64
- Dockerfile.arm64
* https://github.com/actions/runner/releases/tag/v2.322.0
> Update GitHub Actions runner from v2.321.0 to v2.322.0

- Dockerfile.amd64
- Dockerfile.arm64
https://github.com/actions/runner/releases/tag/v2.323.0
> bump runner from 2.322.0 => 2.323.0

- Dockerfile.amd64
- Dockerfile.arm64
* https://github.com/actions/runner/releases/tag/v2.324.0
> Update GitHub Actions runner from v2.323.0 to v2.324.0

- Dockerfile.amd64
- Dockerfile.arm64
* https://github.com/actions/runner/releases/tag/v2.325.0
> Update GitHub Actions Runner from v2.324.0 to v2.325.0

- Dockerfile.amd64
- Dockerfile.arm64
* https://github.com/actions/runner/releases/tag/v2.328.0
> Update GitHub Action Runner from v2.326 to v2.328.0
